#!/usr/bin/env python3
"""Build the MetaMuse Max for Live devices.

    MetaMuse Chords      MIDI Tool (Generate)   chord progressions into a clip
    MetaMuse Bass        MIDI Tool (Transform)  chords -> bassline
    MetaMuse Melody      MIDI Tool (Transform)  chords -> melody
    MetaMuse Chord Keys  MIDI Effect            one key plays a full chord

Each device's script is src/theory.js (shared) + its own file in src/.

Usage:
    python3 build_devices.py                   # build into ./build
    python3 build_devices.py "<User Library>"  # build and install into Live
"""

import sys
from pathlib import Path

from maxpatch import DeviceUI, Patch, write_amxd

HERE = Path(__file__).resolve().parent

# Menu contents. Order must match the arrays in src/*.js.
NOTES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
SCALES = ["Major", "Natural Minor", "Harmonic Minor", "Melodic Minor", "Dorian",
          "Phrygian", "Lydian", "Mixolydian", "Locrian", "Pentatonic Major",
          "Pentatonic Minor", "Blues", "Whole Tone", "Diminished (W-H)"]
CHORD_TYPES = ["Triad (3)", "7th (4)", "9th (5)", "11th (6)", "13th (7)", "5th",
               "add9", "sus2", "sus4", "maj9", "min9", "9 (dom)", "add11", "m/maj7", "dim7", "aug"]

# MIDI Tools live in a panel roughly this size.
TOOL_W, TOOL_H = 152, 146


def js_source(device_file):
    """Shared theory + the device's own script, as one file for [js]."""
    banner = ("// GENERATED by build_devices.py from src/theory.js + src/"
              f"{device_file}. Edit those files and rebuild, not this one.\n\n")
    return banner + (HERE / "src/theory.js").read_text() + "\n" + (HERE / "src" / device_file).read_text()


def midi_tool_core(p, js_text):
    """live.miditool.in/out + js + live.thisdevice, wired the same for every MIDI Tool."""
    tool_in = p.obj("live.miditool.in", 20, 20, inlets=1, outlets=3)
    tool_out = p.obj("live.miditool.out", 20, 420, inlets=1, outlets=0)
    js = p.obj(js_text, 20, 380, inlets=2, outlets=3, width=180)
    this_device = p.obj("live.thisdevice", 520, 20, inlets=1, outlets=3)
    loaded = p.msg("loaded", 520, 50)
    p.connect(tool_in, js, 0, 0)       # notes
    p.connect(tool_in, js, 1, 1)       # context (scale, grid, time selection)
    p.connect(js, tool_out, 0, 0)      # new notes -> clip
    p.connect(js, tool_in, 1, 0)       # control changed -> run again
    p.connect(this_device, loaded, 0, 0)
    p.connect(loaded, js, 0, 0)
    return js


# ─── MetaMuse Chords ─────────────────────────────────────────────────────────

LENGTHS = ["1/2 beat", "1 beat", "2 beats", "3 beats", "1 bar", "6 beats", "2 bars", "4 bars"]
DEGREES = ["-", "I", "II", "III", "IV", "V", "VI", "VII"]
SLOT_LENGTHS = ["Len=", "1/8", "1/4", "1/2", "3/4", "1", "1.5", "2", "3", "4"]  # bars; "Len=" = Length menu
SLOT_INVERSIONS = ["Inv=", "Root", "1st", "2nd", "3rd"]  # "Inv=" = Inversion / Voice Leading
STYLES = ["Block", "Strum Up", "Strum Down", "Arp Up", "Arp Down", "Arp Up-Down", "Arp Random"]
RATES = ["1/64", "1/32", "1/16", "1/8", "1/4", "1/16T", "1/8T"]
PRESETS = ["Presets…", "I V vi IV", "I vi IV V", "vi IV I V", "ii V I", "vi ii V I",
           "I IV V IV", "i VI III VII", "i iv v", "i VII VI V", "Canon (8)",
           "12-bar Blues", "Pop Song (16)"]
NUM_SLOTS = 16
DEFAULT_SLOTS = [1, 5, 6, 4] + [0] * 12


def build_chords():
    p = Patch()
    js = midi_tool_core(p, "js metamuse_chords.js")
    feedback = p.obj("route readout slot slotlen slotinv preset", 200, 420, inlets=1, outlets=6, width=240)
    slot_router = p.obj("route " + " ".join(map(str, range(NUM_SLOTS))), 200, 450,
                        inlets=1, outlets=NUM_SLOTS + 1, width=300)
    len_router = p.obj("route " + " ".join(map(str, range(NUM_SLOTS))), 200, 480,
                       inlets=1, outlets=NUM_SLOTS + 1, width=300)
    p.connect(js, feedback, 2, 0)
    p.connect(feedback, slot_router, 1, 0)
    inv_router = p.obj("route " + " ".join(map(str, range(NUM_SLOTS))), 200, 510,
                       inlets=1, outlets=NUM_SLOTS + 1, width=300)
    p.connect(feedback, len_router, 2, 0)
    p.connect(feedback, inv_router, 3, 0)

    ui = DeviceUI(p, js)

    # The Generate panel is tiny, so controls are split over four pages.
    ui.page("Key")
    ui.menu("Root", "Root", NOTES, 0, [0, 18, 32, 16], "root", "Key root note.")
    ui.menu("Scale", "Scale", SCALES, 0, [34, 18, 118, 16], "scale",
            "Scale or mode the chords are built from.")
    ui.menu("Chord Type", "Type", CHORD_TYPES, 0, [0, 37, 76, 16], "type",
            "Triad (3 notes) to 13th (7 notes) stack notes from the scale, so they follow the mode. The others use a fixed shape on each degree.")
    ui.menu("Length", "Len", LENGTHS, 4, [78, 37, 74, 16], "length",
            "Default length of each chord. Slots set to 'Len=' use this; give a slot its own length on the 1-8 / 9-16 pages.")
    ui.numbox("Octave", "Oct", 0, 6, 3, [0, 56, 48, 16], "octave",
              "Octave of the chord roots (Live naming: C3 = middle C).", "Oct %d")
    ui.numbox("Inversion", "Inv", 0, 3, 0, [50, 56, 48, 16], "inversion",
              "Moves the lowest notes up an octave, for every chord set to 'Inv='. With Voice Leading on, this sets the first chord only.", "Inv %d")
    ui.toggle("Bass", "+ Bass", 0, [100, 56, 52, 16], "bass", "Adds the chord root an octave below.")
    ui.toggle("Clip Scale", "Clip Key", 0, [0, 75, 48, 16], "clipscale",
              "Ignore Key and Scale and use the clip's Scale setting instead.")
    ui.toggle("Fill", "Fill", 1, [50, 75, 48, 16], "fill",
              "On: repeat the progression until the end of the time selection / loop. Off: write it once.")
    preset = ui.menu("Preset", "Preset", PRESETS, 0, [100, 75, 52, 16], "preset",
                     "Load a common progression into the chord slots (up to 16 chords).")
    p.connect(feedback, preset, 4, 0)

    # Each chord slot is a column of three menus: chord, length, inversion.
    # Two groups of four columns fill the page (15 px menus, 1 px apart).
    for page, first in (("1-8", 0), ("9-16", 8)):
        ui.page(page)
        for k in range(8):
            i = first + k
            x, y = (k % 4) * 38, 18 + (k // 4) * 50
            slot = ui.menu(f"Slot {i + 1}", f"Slot{i + 1}", DEGREES, DEFAULT_SLOTS[i],
                           [x, y, 36, 15], f"slot {i}",
                           f"Chord {i + 1} of the progression, as a scale degree. '-' skips it.")
            p.connect(slot_router, slot, i, 0)
            length = ui.menu(f"Len {i + 1}", f"Len{i + 1}", SLOT_LENGTHS, 0,
                             [x, y + 16, 36, 15], f"slotlen {i}",
                             f"Length of chord {i + 1} in bars. 'Len=' uses the Length menu on the Key page.")
            p.connect(len_router, length, i, 0)
            inv = ui.menu(f"Inv {i + 1}", f"Inv{i + 1}", SLOT_INVERSIONS, 0,
                          [x, y + 32, 36, 15], f"slotinv {i}",
                          f"Inversion of chord {i + 1}. 'Inv=' follows the Inversion control (and Voice Leading); "
                          "Root/1st/2nd/3rd fix it for this chord. 3rd needs a 7th chord or bigger.")
            p.connect(inv_router, inv, i, 0)

    ui.page("Feel")
    ui.menu("Style", "Style", STYLES, 0, [0, 18, 76, 16], "style",
            "Block chords, strums (notes staggered by Rate) or arpeggios (one note per Rate step).")
    ui.menu("Rate", "Rate", RATES, 2, [78, 18, 74, 16], "rate",
            "Strum spread per note, or arpeggio step length. Try 1/64 for strums, 1/16 for arps.")
    ui.toggle("Voice Leading", "Voice Leading", 0, [0, 37, 100, 16], "voicelead",
              "Picks inversions automatically so each chord moves as little as possible from the last.")
    ui.numbox("Velocity", "Vel", 1, 127, 100, [102, 37, 50, 16], "velocity", "Note velocity.", "Vel %d")

    readout = ui.readout([0, 116, TOOL_W, 30])
    p.connect(feedback, readout, 0, 0)
    ui.finish_pages([0, 0, TOOL_W, 14])
    p.add("live.line", [0, 146, TOOL_W, 5.0], numinlets=1, numoutlets=0)
    return p.to_json("generator", TOOL_W, TOOL_H,
                     "Chord progressions from any key and mode, written into the clip. From METAMUSE.")


# ─── MetaMuse Bass / Melody ──────────────────────────────────────────────────

BASS_PATTERNS = ["Held", "Pulse", "Root-Fifth", "Octaves", "Walking", "Syncopated", "Push"]
BASS_RATES = ["1/4", "1/8", "1/16", "1/8T"]
MELODY_RHYTHMS = ["Quarters", "8ths", "16ths", "Mixed"]


def build_lines(mode):
    p = Patch()
    js = midi_tool_core(p, f"js metamuse_lines.js {mode}")
    feedback = p.obj("route readout", 200, 420, inlets=1, outlets=2)
    p.connect(js, feedback, 2, 0)
    ui = DeviceUI(p, js)

    if mode == "bass":
        ui.menu("Pattern", "Pattern", BASS_PATTERNS, 1, [0, 0, 100, 16], "pattern",
                "Held: root for the whole chord. Pulse: repeated root. Root-Fifth / Octaves: alternate. "
                "Walking: steps towards the next chord. Syncopated: 3+3+2 groove. Push: hits the next root early.")
        ui.menu("Rate", "Rate", BASS_RATES, 1, [102, 0, 50, 16], "rate", "Step length of the pattern.")
        ui.numbox("Octave", "Oct", 0, 3, 1, [0, 19, 48, 16], "octave",
                  "Bass octave (Live naming: C1 = MIDI 36).", "Oct %d")
        ui.numbox("Gate", "Gate", 10, 100, 90, [50, 19, 48, 16], "gate",
                  "How long each note lasts, as % of its step. Lower = punchier.", "Gate %d")
        ui.numbox("Velocity", "Vel", 1, 127, 100, [100, 19, 52, 16], "velocity", "Note velocity.", "Vel %d")
        top = 40
        description = "Turns the chords in a clip into a bassline. From METAMUSE."
    else:
        ui.menu("Rhythm", "Rhythm", MELODY_RHYTHMS, 1, [0, 0, 76, 16], "rhythm",
                "Note values of the melody. Mixed varies them beat by beat.")
        ui.numbox("Density", "Dens", 0, 100, 60, [78, 0, 74, 16], "density",
                  "How busy the melody is, in %.", "Density %d")
        ui.numbox("Octave", "Oct", 2, 6, 4, [0, 19, 48, 16], "octave",
                  "Melody octave (Live naming: C3 = middle C).", "Oct %d")
        ui.numbox("Variation", "Var", 1, 99, 1, [50, 19, 48, 16], "variation",
                  "Change this for a different melody over the same chords.", "Var %d")
        ui.numbox("Velocity", "Vel", 1, 127, 100, [100, 19, 52, 16], "velocity", "Note velocity.", "Vel %d")
        ui.toggle("Repeat", "Repeat Motif", 1, [0, 38, 100, 16], "repeat",
                  "On: every bar reuses the same rhythm, so the melody has a hook. Off: a new rhythm each bar.")
        top = 59
        description = "Writes a melody that follows the chords in a clip. From METAMUSE."

    readout = ui.readout([0, top, TOOL_W, TOOL_H - top], linecount=6)
    p.connect(feedback, readout, 0, 0)
    p.add("live.line", [0, 146, TOOL_W, 5.0], numinlets=1, numoutlets=0)
    return p.to_json("transformation", TOOL_W, TOOL_H, description)


# ─── MetaMuse Chord Keys ─────────────────────────────────────────────────────

MAPPINGS = ["White Keys", "Snap"]
STRUM_DIRS = ["Up", "Down"]
KEYS_W, KEYS_H = 300, 169


def build_chord_keys():
    p = Patch()
    midi_in = p.obj("midiin", 20, 20, inlets=1, outlets=1)
    js = p.obj("js metamuse_chordkeys.js", 20, 380, inlets=1, outlets=2, width=180)
    midi_out = p.obj("midiout", 20, 420, inlets=1, outlets=0)
    this_device = p.obj("live.thisdevice", 520, 20, inlets=1, outlets=3)
    loaded = p.msg("loaded", 520, 50)
    feedback = p.obj("route readout", 200, 420, inlets=1, outlets=2)
    p.connect(midi_in, js, 0, 0)
    p.connect(js, midi_out, 0, 0)
    p.connect(js, feedback, 1, 0)
    p.connect(this_device, loaded, 0, 0)
    p.connect(loaded, js, 0, 0)

    ui = DeviceUI(p, js)
    for text, x, y, w in (("Key", 8, 4, 32), ("Scale / Mode", 44, 4, 110), ("Keys", 158, 4, 70),
                          ("Chord", 232, 4, 60), ("Octave", 8, 42, 44), ("Inversion", 56, 42, 44),
                          ("Strum ms", 196, 42, 48), ("Strum", 248, 42, 44)):
        ui.label(text, [x, y, w, 12], fontsize=9.0)

    ui.menu("Root", "Root", NOTES, 0, [8, 16, 32, 16], "root", "Key root note.")
    ui.menu("Scale", "Scale", SCALES, 0, [44, 16, 110, 16], "scale", "Scale or mode of the chords.")
    ui.menu("Keys", "Keys", MAPPINGS, 0, [158, 16, 70, 16], "mapping",
            "White Keys: C D E F G A B always play chords I-VII of your key. "
            "Snap: any key plays the chord on the nearest scale note.")
    ui.menu("Chord Type", "Type", CHORD_TYPES, 0, [232, 16, 60, 16], "type",
            "Triad (3 notes) to 13th (7 notes) follow the mode; the others are fixed shapes.")
    ui.numbox("Octave", "Oct", -2, 2, 0, [8, 54, 44, 16], "octshift",
              "Shift the chords up or down by octaves.", "%d")
    ui.numbox("Inversion", "Inv", 0, 3, 0, [56, 54, 44, 16], "inversion",
              "Moves the lowest notes up an octave.", "%d")
    ui.toggle("Bass", "+ Bass", 0, [104, 54, 40, 16], "bass", "Adds the chord root an octave below.")
    ui.toggle("Voice Leading", "Smooth", 1, [148, 54, 44, 16], "voicelead",
              "Voice leading: each chord uses the inversion closest to the last one you played.")
    ui.numbox("Strum", "Strum", 0, 200, 0, [196, 54, 48, 16], "strum",
              "Delay between the notes of each chord, in milliseconds. 0 = all at once.", "%d")
    ui.menu("Strum Dir", "Dir", STRUM_DIRS, 0, [248, 54, 44, 16], "strumdir", "Strum low-to-high or high-to-low.")

    readout = ui.readout([8, 84, KEYS_W - 16, 76], fontsize=13.0, linecount=3)
    p.connect(feedback, readout, 0, 0)
    return p.to_json("midi_effect", KEYS_W, KEYS_H,
                     "Play one key, get a full chord in your key and mode. From METAMUSE.")


# ─── BUILD / INSTALL ─────────────────────────────────────────────────────────

# (device file, builder, script name, script source, User Library subfolder)
DEVICES = [
    ("MetaMuse Chords.amxd", build_chords, "metamuse_chords.js", "chords.js",
     "MIDI Tools/Max Generators"),
    ("MetaMuse Bass.amxd", lambda: build_lines("bass"), "metamuse_lines.js", "lines.js",
     "MIDI Tools/Max Transformations"),
    ("MetaMuse Melody.amxd", lambda: build_lines("melody"), "metamuse_lines.js", "lines.js",
     "MIDI Tools/Max Transformations"),
    ("MetaMuse Chord Keys.amxd", build_chord_keys, "metamuse_chordkeys.js", "chordkeys.js",
     "Presets/MIDI Effects/Max MIDI Effect"),
]

TYPES = {"MIDI Tools/Max Generators": "generator",
         "MIDI Tools/Max Transformations": "transformation",
         "Presets/MIDI Effects/Max MIDI Effect": "midi_effect"}


def main():
    user_library = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    for amxd, builder, script, source, subfolder in DEVICES:
        out_dir = user_library / subfolder if user_library else HERE / "build" / subfolder
        out_dir.mkdir(parents=True, exist_ok=True)
        write_amxd(builder(), TYPES[subfolder], out_dir / amxd)
        (out_dir / script).write_text(js_source(source))  # the js sits next to its device
        print(f"Wrote {out_dir / amxd}")


if __name__ == "__main__":
    main()
