// GENERATED by build_devices.py from src/theory.js + src/keys.js. Edit those files and rebuild, not this one.

// ─── Keywise shared music theory ────────────────────────────────────────────
//
// Scales, chord shapes, chord names and voice leading used by every Keywise
// device. build_devices.py pastes this file in front of each device's own
// script, so edit it here and rebuild — the built .js files are generated.
//
// Written in ES5 so it runs in Max's classic [js] object.

var NOTES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];

// Order must match SCALES in build_devices.py
var SCALES = [
    ["Major",            [0, 2, 4, 5, 7, 9, 11]],
    ["Natural Minor",    [0, 2, 3, 5, 7, 8, 10]],
    ["Harmonic Minor",   [0, 2, 3, 5, 7, 8, 11]],
    ["Melodic Minor",    [0, 2, 3, 5, 7, 9, 11]],
    ["Dorian",           [0, 2, 3, 5, 7, 9, 10]],
    ["Phrygian",         [0, 1, 3, 5, 7, 8, 10]],
    ["Lydian",           [0, 2, 4, 6, 7, 9, 11]],
    ["Mixolydian",       [0, 2, 4, 5, 7, 9, 10]],
    ["Locrian",          [0, 1, 3, 5, 6, 8, 10]],
    ["Pentatonic Major", [0, 2, 4, 7, 9]],
    ["Pentatonic Minor", [0, 3, 5, 7, 10]],
    ["Blues",            [0, 3, 5, 6, 7, 10]],
    ["Whole Tone",       [0, 2, 4, 6, 8, 10]],
    ["Diminished (W-H)", [0, 2, 3, 5, 6, 8, 9, 11]]
];

// Order must match CHORD_TYPES in build_devices.py.
// "steps" = stack every other scale note (diatonic, follows the mode).
//           These are the main chord sizes: 3, 4, 5, 6 and 7 notes.
// "semis" = fixed shape built on each scale degree (same as the web app).
var CHORD_TYPES = [
    { label: "Triad",    steps: [0, 2, 4] },
    { label: "7th",      steps: [0, 2, 4, 6] },
    { label: "9th",      steps: [0, 2, 4, 6, 8] },
    { label: "11th",     steps: [0, 2, 4, 6, 8, 10] },
    { label: "13th",     steps: [0, 2, 4, 6, 8, 10, 12] },
    { label: "5th",      semis: [0, 7],             suffix: "5" },
    { label: "add9",     semis: [0, 4, 7, 14],      suffix: "add9" },
    { label: "sus2",     semis: [0, 2, 7],          suffix: "sus2" },
    { label: "sus4",     semis: [0, 5, 7],          suffix: "sus4" },
    { label: "maj9",     semis: [0, 4, 7, 11, 14],  suffix: "maj9" },
    { label: "min9",     semis: [0, 3, 7, 10, 14],  suffix: "m9" },
    { label: "9 (dom)",  semis: [0, 4, 7, 10, 14],  suffix: "9" },
    { label: "add11",    semis: [0, 4, 7, 17],      suffix: "add11" },
    { label: "m/maj7",   semis: [0, 3, 7, 11],      suffix: "m(maj7)" },
    { label: "dim7",     semis: [0, 3, 6, 9],       suffix: "dim7" },
    { label: "aug",      semis: [0, 4, 8],          suffix: "aug" },
    // Not in any menu: the fills use these so a V chord always pulls home,
    // even in minor keys (E7 rather than Em7 in A minor).
    { label: "dominant 7", semis: [0, 4, 7, 10],    suffix: "7" },
    { label: "dominant",   semis: [0, 4, 7],        suffix: "" }
];

var ROMAN = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII"];

// Semitone offsets (from the chord root) for scale degree degIdx (0-based).
function chordShape(intervals, degIdx, type) {
    var def = CHORD_TYPES[type];
    if (def.semis) return def.semis.slice();
    var len = intervals.length;
    var base = intervals[degIdx];
    var out = [];
    for (var i = 0; i < def.steps.length; i++) {
        var pos = degIdx + def.steps[i];
        out.push(intervals[pos % len] + 12 * Math.floor(pos / len) - base);
    }
    return out;
}

// ─── CHORD NAMES ─────────────────────────────────────────────────────────────
// Name a diatonic shape from its intervals, e.g. [0,3,7,10] -> "m7",
// [0,4,7,10,14,17,21] -> "13", [0,4,7,11,14,18] -> "maj9(#11)".
// Returns null for stacks with no common name (e.g. pentatonic stacks).

var TRIAD_NAMES = { "4,7": "", "3,7": "m", "3,6": "dim", "4,8": "aug", "2,7": "sus2", "5,7": "sus4" };

// Triad + 7th -> name pattern; {n} becomes 7, 9, 11 or 13.
var SEVENTH_NAMES = {
    "4,7,11": "maj{n}", "4,7,10": "{n}", "3,7,10": "m{n}", "3,6,10": "m{n}b5",
    "3,6,9": "dim{n}", "3,7,11": "m(maj{n})", "4,8,11": "maj{n}#5", "4,8,10": "{n}#5"
};

// Upper extensions: which pitch class is "natural", and names for altered ones.
var EXTENSIONS = [
    { n: 9,  natural: 2, altered: { 1: "b9", 3: "#9" } },
    { n: 11, natural: 5, altered: { 6: "#11", 4: "b11" } },
    { n: 13, natural: 9, altered: { 8: "b13", 10: "#13" } }
];

function qualityName(shape) {
    var pcs = shape.map(function (s) { return s % 12; });
    if (pcs.length === 3) {
        var t = pcs.slice(1).join(",");
        return TRIAD_NAMES.hasOwnProperty(t) ? TRIAD_NAMES[t] : null;
    }
    var base = pcs.slice(1, 4).join(",");
    if (!SEVENTH_NAMES.hasOwnProperty(base)) return null;

    // The highest natural extension names the chord (C9, C11, C13) as long as
    // everything below it is natural too; altered ones go in brackets.
    var n = 7, alts = [];
    for (var i = 4; i < pcs.length; i++) {
        var ext = EXTENSIONS[i - 4];
        if (pcs[i] === ext.natural && !alts.length) n = ext.n;
        else if (pcs[i] === ext.natural) alts.push(String(ext.n));
        else if (ext.altered.hasOwnProperty(pcs[i])) alts.push(ext.altered[pcs[i]]);
        else return null;
    }
    return SEVENTH_NAMES[base].replace("{n}", n) + (alts.length ? "(" + alts.join(",") + ")" : "");
}

// Full chord name for a root pitch class and shape, e.g. "Am7" or "C-E-A".
function chordName(rootPc, shape, def) {
    var suffix = (def && def.suffix !== undefined) ? def.suffix : qualityName(shape);
    if (suffix !== null) return NOTES[rootPc] + suffix;
    return shape.map(function (s) { return NOTES[(rootPc + s) % 12]; }).join("-");
}

// Roman numeral, lowercase for minor/diminished chords.
function romanFor(degIdx, shape) {
    var r = ROMAN[degIdx] || String(degIdx + 1);
    var third = shape.length > 1 ? shape[1] % 12 : 4;
    var fifth = shape.length > 2 ? shape[2] % 12 : 7;
    if (third === 3) r = r.toLowerCase();
    if (third === 3 && fifth === 6) r += (shape.length > 3 && shape[3] % 12 === 10) ? "ø" : "°";
    if (third === 4 && fifth === 8) r += "+";
    return r;
}

// ─── VOICE LEADING ───────────────────────────────────────────────────────────
// Given the previous chord's notes and the next chord's notes, try every
// inversion of the next chord in nearby octaves and keep the one whose notes
// move the least. A small pull towards `anchor` (an average pitch) stops a
// long progression drifting up or down the keyboard.

function mean(a) {
    var sum = 0;
    for (var i = 0; i < a.length; i++) sum += a[i];
    return sum / a.length;
}

function ascending(a) {
    return a.slice().sort(function (x, y) { return x - y; });
}

function movement(prev, cand) {
    if (prev.length !== cand.length) return Math.abs(mean(prev) - mean(cand)) * cand.length;
    var cost = 0;
    for (var i = 0; i < cand.length; i++) cost += Math.abs(prev[i] - cand[i]);
    return cost;
}

function smoothestVoicing(prev, next, anchor) {
    var base = ascending(next);
    prev = ascending(prev);
    var best = base, bestCost = Infinity;
    for (var k = 0; k < base.length; k++) {
        var inv = base.slice();
        for (var r = 0; r < k; r++) inv.push(inv.shift() + 12);
        for (var shift = -24; shift <= 12; shift += 12) {
            var cand = inv.map(function (p) { return p + shift; });
            if (cand[0] < 0 || cand[cand.length - 1] > 127) continue;
            var cost = movement(prev, cand) + 0.5 * Math.abs(mean(cand) - anchor);
            if (cost < bestCost) { bestCost = cost; best = cand; }
        }
    }
    return best;
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────

// Small repeatable random generator: the same seed always gives the same
// sequence, so pressing Generate again with the same settings is stable.
function seededRandom(seed) {
    var x = (seed * 9301 + 49297) % 233280;
    return function () {
        x = (x * 9301 + 49297) % 233280;
        return x / 233280;
    };
}

// Time range to write into: Live's time selection, if the context has one.
function selectionRange(ctx) {
    var sel = ctx && (ctx.time_selection || ctx.selection);
    if (sel && typeof sel.start_time === "number" && typeof sel.end_time === "number" &&
        sel.end_time > sel.start_time) {
        return { start: sel.start_time, end: sel.end_time };
    }
    return null;
}

// ─── FILLS ───────────────────────────────────────────────────────────────────
// A fill replaces the end of a phrase. Every device has a "Fill" menu (what
// to play) and an "Every" menu (where): the times at which phrases end.
// Order must match FILL_EVERY in build_devices.py.
var FILL_EVERY = ["Each Pass", "End of Clip", "Every 4 Bars", "Every 8 Bars"];

// Phrase ends between start and end (in beats), for an "Every" choice.
// passLength is how long one pass of the progression lasts. A fill needs
// `room` beats before its phrase end, so ends too close to the start are skipped.
function fillPoints(every, start, end, passLength, room) {
    var step = { "Each Pass": passLength, "Every 4 Bars": 16, "Every 8 Bars": 32 }[FILL_EVERY[every]];
    var points = [];
    if (step > 0) {
        for (var p = start + step; p < end - 1e-6; p += step) points.push(p);
    }
    points.push(end);   // the end of the clip always gets one
    return points.filter(function (p) { return p - room >= start - 1e-6; });
}

// Read a dictionary arriving from live.miditool.in as a plain JS object.
function readDict(name) {
    return JSON.parse(new Dict(name).stringify());
}

// Send notes to live.miditool.out (outlet 0) as a dictionary.
function sendNotes(dictName, notes) {
    var out = new Dict(dictName);
    out.parse(JSON.stringify({ notes: notes }));
    outlet(0, "dictionary", out.name);
}

// ─── Keywise Keys (MIDI Effect) ──────────────────────────────────────
//
// Play one key, hear a full chord in your chosen key and mode.
//
//   White Keys mode: the white keys always play the scale's chords in order,
//                    whatever key you pick: C = I, D = ii, E = iii, F = IV...
//                    (black keys are ignored).
//   Snap mode:       any key plays the chord built on the nearest scale note
//                    at or below it.
//
// Patch wiring (see build_devices.py):
//   inlet 0  : raw MIDI bytes from [midiin] (ints) and UI messages
//   outlet 0 : raw MIDI bytes -> [midiout]
//   outlet 1 : UI feedback -> [route readout]

inlets = 1;
outlets = 2;

// Order must match the menus in build_devices.py.
var MAPPINGS = ["White Keys", "Snap"];
var STRUM_DIRS = ["Up", "Down"];
var WHITE_KEYS = [0, 2, 4, 5, 7, 9, 11];  // C D E F G A B -> degrees 1-7

var state = {
    root: 0,
    scale: 0,
    mapping: 0,
    type: 0,
    octShift: 0,
    inversion: 0,
    bass: 0,
    voiceLead: 1,
    strum: 0,          // ms between notes
    strumDir: 0
};

// ─── CHORD FOR A KEY (pure logic, testable in Node) ─────────────────────────

// Which scale degree and root pitch an incoming key plays, or null to ignore.
function keyToChordRoot(st, pitch) {
    var intervals = SCALES[st.scale][1];
    var len = intervals.length;
    var octave = Math.floor(pitch / 12);   // MIDI octave of the key pressed

    if (MAPPINGS[st.mapping] === "White Keys") {
        var white = WHITE_KEYS.indexOf(pitch % 12);
        if (white < 0) return null;
        var degIdx = white % len;
        var extraOct = Math.floor(white / len);   // short scales wrap upwards
        return {
            degIdx: degIdx,
            rootMidi: (octave + extraOct + st.octShift) * 12 + st.root + intervals[degIdx]
        };
    }

    // Snap: the scale note at or below the key pressed.
    var rel = ((pitch - st.root) % 12 + 12) % 12;
    var deg = 0;
    for (var i = 0; i < len; i++) if (intervals[i] <= rel) deg = i;
    return { degIdx: deg, rootMidi: pitch - (rel - intervals[deg]) + st.octShift * 12 };
}

// The notes (low to high) and name of the chord for one key press.
function chordForKey(st, pitch, prevVoicing) {
    var r = keyToChordRoot(st, pitch);
    if (!r) return null;
    var intervals = SCALES[st.scale][1];
    var shape = chordShape(intervals, r.degIdx, st.type);
    var upper = shape.map(function (s) { return r.rootMidi + s; });
    for (var i = 0; i < st.inversion % upper.length; i++) upper.push(upper.shift() + 12);
    if (st.voiceLead && prevVoicing && prevVoicing.length) {
        upper = smoothestVoicing(prevVoicing, upper, mean(upper));
    }
    var all = upper.slice();
    if (st.bass) all.push(r.rootMidi - 12);
    return {
        upper: upper,
        pitches: ascending(all).filter(function (p) { return p >= 0 && p <= 127; }),
        name: romanFor(r.degIdx, shape) + "  " + chordName((st.root + intervals[r.degIdx]) % 12, shape, CHORD_TYPES[st.type])
    };
}

// ─── LIVE PLAYING ────────────────────────────────────────────────────────────

var lastVoicing = null;
var held = {};       // input pitch -> { sent: [pitches], pending: [Task] }
var soundCount = {}; // output pitch -> how many held keys are sounding it

function send(status, data1, data2) {
    outlet(0, status);
    outlet(0, data1);
    outlet(0, data2);
}

function playOn(channel, pitch, vel) {
    var chord = chordForKey(state, pitch, lastVoicing);
    if (!chord) return;
    lastVoicing = chord.upper;
    outlet(1, "readout", "set", chord.name);

    var order = STRUM_DIRS[state.strumDir] === "Down" ? chord.pitches.slice().reverse() : chord.pitches;
    var entry = { sent: [], pending: [] };
    held[pitch] = entry;
    order.forEach(function (p, k) {
        var start = function () {
            soundCount[p] = (soundCount[p] || 0) + 1;
            entry.sent.push(p);
            send(0x90 | channel, p, vel);
        };
        if (state.strum > 0 && k > 0 && typeof Task !== "undefined") {
            var task = new Task(start);
            entry.pending.push(task);
            task.schedule(state.strum * k);
        } else {
            start();
        }
    });
}

function playOff(channel, pitch) {
    var entry = held[pitch];
    if (!entry) return;
    delete held[pitch];
    entry.pending.forEach(function (t) { t.cancel(); });
    entry.sent.forEach(function (p) {
        soundCount[p] -= 1;
        if (soundCount[p] <= 0) {
            delete soundCount[p];
            send(0x80 | channel, p, 0);
        }
    });
}

// ─── MIDI BYTE PARSER ────────────────────────────────────────────────────────
// [midiin] delivers raw bytes. Note on/off become chords; everything else
// (CCs, pitch bend, sysex, clock...) passes straight through.

var status = 0, data = [], inSysex = false;

function dataLength(st) {
    var type = st & 0xF0;
    if (type === 0xC0 || type === 0xD0) return 1;
    if (st === 0xF1 || st === 0xF3) return 1;
    if (st === 0xF2) return 2;
    if (st >= 0xF4) return 0;
    return 2;
}

function msg_int(b) {
    if (b >= 0xF8) { outlet(0, b); return; }                 // realtime: pass through
    if (b === 0xF0) { inSysex = true; outlet(0, b); return; }
    if (inSysex) { outlet(0, b); if (b === 0xF7) inSysex = false; return; }
    if (b >= 0x80) {
        status = b; data = [];
        if (dataLength(b) === 0) outlet(0, b);
        return;
    }
    if (!status) return;
    data.push(b);
    if (data.length < dataLength(status)) return;

    var type = status & 0xF0, channel = status & 0x0F;
    if (type === 0x90 && data[1] > 0) playOn(channel, data[0], data[1]);
    else if (type === 0x80 || type === 0x90) playOff(channel, data[0]);
    else { outlet(0, status); data.forEach(function (d) { outlet(0, d); }); }
    data = [];   // keep status for running status
}

// ─── UI ──────────────────────────────────────────────────────────────────────

function idleText() {
    return NOTES[state.root] + " " + SCALES[state.scale][0] +
        (MAPPINGS[state.mapping] === "White Keys" ? " · white keys: C=I D=ii E=iii F=IV G=V A=vi B=vii" : " · play any key");
}

function changed() {
    lastVoicing = null;
    outlet(1, "readout", "set", idleText());
}

function root(v)      { state.root = v | 0; changed(); }
function scale(v)     { state.scale = v | 0; changed(); }
function mapping(v)   { state.mapping = v | 0; changed(); }
function type(v)      { state.type = v | 0; changed(); }
function octshift(v)  { state.octShift = v | 0; changed(); }
function inversion(v) { state.inversion = v | 0; changed(); }
function bass(v)      { state.bass = v ? 1 : 0; changed(); }
function voicelead(v) { state.voiceLead = v ? 1 : 0; changed(); }
function strum(v)     { state.strum = Math.max(0, v | 0); }
function strumdir(v)  { state.strumDir = v | 0; }

function loaded() { changed(); }
